### ISSUE TITLE
Symfony 4.0 compatibility

### ISSUE THREAD

**Issue by matthieuwerner** [hpatoio/BitlyBundle#6]
Hello,

There are a deprecated alert on this line :
```
hpatoio_bitly.log.monolog:
        class: "Guzzle\\Plugin\\Log\\LogPlugin"
        arguments: ["@hpatoio_bitly.log.monolog.adapter", %hpatoio_bitly.log.format%]
```

`Not quoting the scalar "%hpatoio_bitly.log.format%" starting with the "%" indicator character is deprecated since Symfony 3.1 and will throw a ParseException in 4.0 in "/var/www/html/vendor/hpatoio/bitly-bundle/DependencyInjection/../Resources/config/monolog_service.yml" on line 4.`

The quotes of "%hpatoio_bitly.log.format%" are missing.

Is it possible to fix this ?

Best regards.

**Comment by hpatoio** [comment]
I've pushed a fix. Please point to `dev-master` and update the package. I'll tag a minor release once you confirm.

**Comment by matthieuwerner** [comment]
Great, thank you :)
