### ISSUE TITLE
reset() method should be implemented in DataCollector/BitlyDataCollector.php

### ISSUE THREAD

**Issue by dnegometyanov** [hpatoio/BitlyBundle#7]
reset() method should be implemented in DataCollector/BitlyDataCollector.php to implement symfony/http-kernel/DataCollector/DataCollectorInterface

**Comment by hpatoio** [comment]
Lemmi know if is ok for you. I'll tag a new release once you confirm.

**Comment by hpatoio** [comment]
@dnegometyanov can you confirm that it works ?
